site_name: Weni CLI Documentation
site_description: Documentation for the Weni Command Line Interface
site_url: https://weni-ai.github.io/weni-cli/
repo_url: https://github.com/weni-ai/weni-cli
repo_name: weni-ai/weni-cli

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    # Modo claro
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Modo escuro
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono

# Customização adicional
extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - def_list
  - meta
  - md_in_html
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/weni-ai
  generator: false

nav:
  - Home:  index.md
  - Community: community/community.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Authentication: getting-started/authentication.md
  - Core Concepts:
    - Agents: core-concepts/agents.md
    - Skills: core-concepts/skills.md
    - Credentials: core-concepts/credentials.md
    - Contact Fields: core-concepts/contact-fields.md
  - Run:
    - Run: run/skill-run.md
  - Examples:
    - Example Gallery: examples/gallery.md
  - Utils:
    - Command Glossary: utils/commands-glossary.md