name: Publish to PyPI

on:
  push:
    tags: 
    - '*.*.*'
    - '*.*.*a*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry self update 1.8.5

      - name: Verify Poetry installation
        run: poetry --version

      - name: Build package
        run: poetry build

      - name: Publish to pypi
        shell: bash
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false